name: Publish Sphinx Documentation

on: [push, pull_request]  # No need to limit to certain branches

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for sphinx-multiversion to see all branches/tags
          lfs: true
      - name: create site
        run: |
          mkdir -p public
          echo ${{github.ref}} > public/index.html
      - name: multipages
        uses: rkdarst/gh-pages-multibranch@dev
        if: ${{ github.event_name == 'push' }}
        with:
          directory: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
          force_orphan: true    
 

      