name: Publish Deploy Sphinx Multiversion Docs

on:
  push:
    branches:
      - '**'      # All branches
    tags:
      - '**'      # All tags

    # on: [push, pull_request] 

jobs:
  build_and_publish_docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Required to push to gh-pages branch
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed by sphinx-multiversion to see all branches/tags

  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -e .
        pip install sphinx furo sphinx_multiversion
    - name: Build documentation with sphinx-multiversion
      run: |
        sphinx-multiversion docs _build/html

    
    - name: Create dynamic index.html with version links
      run: |
        INDEX_FILE="_build/html/index.html"
        echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Documentation Versions</title></head><body>" > $INDEX_FILE
        echo "<h1>Documentation Versions</h1><ul>" >> $INDEX_FILE
        for d in $(ls -d _build/html/*/ | grep -v '^_build/html/_static'); do
          version=$(basename "$d")
          echo "<li><a href=\"${version}/index.html\">${version}</a></li>" >> $INDEX_FILE
        done
        echo "</ul></body></html>" >> $INDEX_FILE

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _build/html
        force_orphan: true
